### ISSUE TITLE
String implicit/explicit conversion issues/stance

### ISSUE THREAD

**Issue by Meigs2** [Lippur/StrictId#4]
Hi!

I'm loving the library. However there's one slight issue with the current auto-conversions between Id<T> <-> string.

First, it seems that some conversions are implicit, while others are explicit, for example between `Id<T>` and `Id`, `string` -> `Id` is implicit, while it is explicit for `string -> Id<T>`. Seems the API isn't consistent. This caused some EF Core queries I was trying to make to fail, as the query was actually *downcasting* the ID column of my database to a string, and the string representation of ID in Sql Server is not the same as Ulid's Base32 representation, causing the query to fail.

Is there a reason certain casts are implicit vs explicit? If not, I think the best approach is to make all **upcasts** to `Id` and `Id<T>` implicit, and all **downcasts** explicit. This way you can't get into the scenario I was in where I thought a comparison was upcasting to Id<T> and not downcasting Id<T>. I feel like if you're ever using this library you're really wanting to operate only on the `Id` types, and if you want to do so then you can easily call `ToString()` to `ToId()`.

Thoughts?

**Comment by Lippur** [comment]
Hi!

You're absolutely right!
I got an email about this earlier this week as well, with exactly the same concern. I initially made the casts implicit to make the library more interoperable and easier to adopt. However, looking back at it now, this was clearly a judgement error on my part - type information should never be lost implicitly. This also causes problems with comparison, since two different ID types can be compared to each other in, for example, a LINQ `Where` lambda, with only an IDE warning about an implicit cast but no compiler error. That clearly works against the purpose and goal of the library.

I will push a new version this week, removing all implicit casts which lose type information, just as you suggest. It's a far better approach.

**Comment by Lippur** [comment]
This change has been published as version 1.1.0.

**Comment by Meigs2** [comment]
Awesome! Thank you for the quick response.
