### ISSUE TITLE
Will .NET 9 version be available? Current 8.0.0 has major vulnerabilities 

### ISSUE THREAD

**Issue by indcoder** [Lippur/StrictId#5]
Will there be a .NET 9 compatible released?

Because right now the 8.0.0 versions has a few major vulnerabilities
<img width="326" alt="image" src="https://github.com/user-attachments/assets/ab5ca551-fb1c-46fa-bdb9-065aa6eb022a">

<img width="331" alt="image" src="https://github.com/user-attachments/assets/060093d7-31cd-4ae0-8c6b-a00ceea80a26">

Moreover EF Core 9 has some great improvements especially [LINQ queries](https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-9.0/whatsnew#significantly-improved-linq-querying-capabilities)

**Comment by Lippur** [comment]
The library is already compatible with .NET 9, it will also become the main targeted version once .NET 9 is officially released.

You can fix the vulnerabilities by changing the NuGet installation policy to use the latest minor version instead of the lowest. There is no reason to use version 8.0.0 specifically, it is just the lowest compatible version. Any newer (minor) version will work just as well.

**Comment by Lippur** [comment]
Version `1.2.0` targeting .NET 9 has been released!
